import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
const root = path.resolve(import.meta.dirname, '../..');
execFileSync(process.execPath, ['scripts/sync-creator-credit.mjs', '--check'], {cwd:root, stdio:'pipe'});
const fragment = fs.readFileSync(path.join(root, 'frontend/templates/creator-credit.html'), 'utf8');
assert.match(fragment, /text-align:center/);
assert.match(fragment, /min-height:44px/);
assert.match(fragment, /max-width:100%/);
assert.match(fragment, /padding:16px 16px 24px/, 'compact desktop signature, not a second footer');
assert.match(fragment, /width:160px/, 'owner-requested smaller logo');
assert.match(fragment, /@media\(max-width:600px\).*padding-bottom:160px/, 'MBSH-specific mobile guide clearance');
assert.doesNotMatch(fragment, /padding-bottom:192px|16px 88px/);
assert.match(fragment, /aria-label="Created by FAMtastic Designs/);
assert.match(fragment, /https:\/\/famtasticdesigns.com\/\?utm_source=mbsh96reunion&amp;utm_medium=creator_credit/);
assert.doesNotMatch(fragment, /onclick|<script|target="_blank"/);
assert.equal((fragment.match(/<img /g) || []).length, 1);
console.log('PASS creator credit: final static row, original asset, source-only attribution, no JS dependency');
