import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';

const root=resolve(import.meta.dirname,'../..');
const api=readFileSync(resolve(root,'frontend/portal/js/portal-api.js'),'utf8');
const ui=readFileSync(resolve(root,'frontend/portal/index.html'),'utf8');
const app=readFileSync(resolve(root,'frontend/portal/js/portal.js'),'utf8');
const staff=readFileSync(resolve(root,'frontend/portal/js/portal-staff.js'),'utf8');
const config=readFileSync(resolve(root,'frontend/portal/js/portal-config.js'),'utf8');
const adminUi=readFileSync(resolve(root,'frontend/portal/committee/index.html'),'utf8');
const adminApp=readFileSync(resolve(root,'frontend/portal/js/committee-workspace.js'),'utf8');
const adminHarry=readFileSync(resolve(root,'frontend/portal/js/admin-harry-guide.js'),'utf8');
const triviaUi=readFileSync(resolve(root,'frontend/portal/js/trivia.js'),'utf8');
const triviaAdmin=readFileSync(resolve(root,'frontend/portal/js/admin-trivia.js'),'utf8');
const auth=['login','register','recovery','verify','reset'].map(name=>readFileSync(resolve(root,`frontend/portal/auth/${name}.html`),'utf8')).join('\n');
const backend={};
for(const name of ['register','login','logout','forgot-password','reset-password','verify-email','profile','preferences','tickets','media','suggestions','notifications','session','my-event','conversations']) backend[name]=readFileSync(resolve(root,`backend/portal/${name}.php`),'utf8');

for(const endpoint of ['session.php','register.php','login.php','logout.php','forgot-password.php','reset-password.php','verify-email.php','profile.php','preferences.php','tickets.php','media.php','suggestions.php','notifications.php','my-event.php','conversations.php']) assert.match(api,new RegExp(endpoint.replace('.','\\.')),`missing ${endpoint}`);
assert.match(api,/credentials:\s*'same-origin'/,'requests must use same-origin credentials');
assert.match(api,/X-CSRF-Token/,'authenticated writes must send CSRF');
assert.match(config,/mode:\s*'api'/,'production default must be API mode');
assert.match(api,/config\.mode === 'demo'/,'demo adapter must require explicit configuration');
assert.doesNotMatch(api+app,/localStorage|sessionStorage/,'secrets/session state must not enter browser storage');
for(const field of ['title','file','caption','event_year','consent_to_publish','subject','message','event_updates','memory_updates','promotional_email','sms_notifications']) assert.match(ui,new RegExp(`name="${field}"`),`missing UI field ${field}`);
for(const field of ['email','password','first_name','last_name']) assert.match(auth,new RegExp(`name="${field}"`),`missing auth field ${field}`);
for(const [file,fields] of Object.entries({register:['email','first_name','last_name','password'],preferences:['event_updates','memory_updates','promotional_email','sms_notifications'],media:['title','caption','event_year','consent_to_publish'],suggestions:['category','subject','message']})) for(const field of fields) assert.match(backend[file],new RegExp(`['"]${field}['"]`),`backend ${file} contract no longer exposes ${field}`);
assert.match(backend.session,/csrf_token/,'session must bootstrap CSRF');
for(const file of ['logout','profile','preferences','media','suggestions','notifications','my-event','conversations']) assert.match(backend[file],/fam_require_attendee_csrf/,'authenticated mutation must require CSRF');
assert.match(api,/updateMyEvent/,'RSVP must use its authenticated API');
assert.match(app,/api\.updateMyEvent/,'RSVP form must perform a real authenticated write');
for(const method of ['updateMedia','withdrawMedia','updateSuggestion','closeSuggestion']) assert.match(api,new RegExp(`${method}:`),`missing attendee lifecycle API ${method}`);
for(const marker of ['data-media-list','data-suggestion-list']) assert.match(ui,new RegExp(marker),`missing attendee lifecycle surface ${marker}`);
for(const call of ['api.updateMedia','api.withdrawMedia','api.updateSuggestion','api.closeSuggestion']) assert.match(app,new RegExp(call.replace('.','\\.')),`attendee UI does not call ${call}`);
assert.doesNotMatch(ui,/type="submit" disabled>Save reunion details/,'RSVP submit must be usable');
for(const view of ['committee','review','people','inbox','communications','operations']) assert.match(ui,new RegExp(`data-view-panel="${view}" data-staff-only hidden`),`staff view ${view} must fail closed`);
assert.match(ui,/data-mode-switch hidden/,'staff mode switch must fail closed');
assert.match(staff,/if\(!candidate\?\.authorized\)return/,'staff UI must require server authorization');
assert.match(staff,/location\.href='\/portal\/admin\/'/,'authorized staff must enter the permission-filtered admin portal');
assert.match(staff,/No placeholder records are being shown/,'unavailable staff APIs must not render pretend data');
for(const marker of ['data-coach-title','data-coach-lesson','data-coach-checklist','data-coach-boundary']) assert.match(adminUi,new RegExp(marker),`admin teaching surface missing ${marker}`);
assert.match(adminUi,/data-harry-admin-ask/,'interactive admin Harry question form missing');
assert.match(adminHarry,/Media approvals/,'Harry must route media questions to the moderated workspace');
assert.match(adminHarry,/Tickets & check-in/,'Harry must route ticket questions to the authoritative workflow');
assert.match(ui,/data-view-panel="trivia"/,'attendee trivia view missing');
assert.match(api,/trivia\.php/,'trivia API adapter missing');
assert.match(triviaUi,/selected_index/,'attendee trivia answer flow missing');
assert.match(triviaAdmin,/manage_event_content/,'trivia studio must fail closed by capability');
for(const lesson of ['command','people','dinner','harry','review','messages','tickets','content','access','platform','delivery','audit']) assert.match(adminApp,new RegExp(`${lesson}:\\[`),`missing Harry admin lesson for ${lesson}`);
assert.match(adminApp,/required&&!staff\?\.capabilities\?\.includes\(required\)/,'direct admin panel routing must enforce capabilities');
console.log('portal contract: PASS');
