<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/_bootstrap.php';
$method=fam_portal_json_method(['GET','POST']);$staff=fam_require_portal_staff($pdo,'view_inbox');$public=trim((string)($_GET['id']??''));
if(!preg_match('/^[a-f0-9-]{36}$/i',$public))fam_json_response(400,['error'=>'invalid_record']);
$q=$pdo->prepare("SELECT c.id,c.public_id,c.subject,c.status,c.priority,c.response_due_at,c.updated_at,a.email,CONCAT(p.first_name,' ',p.last_name) participant_name FROM portal_conversations c LEFT JOIN attendee_accounts a ON a.id=c.attendee_id LEFT JOIN attendee_profiles p ON p.attendee_id=c.attendee_id WHERE c.public_id=?");$q->execute([$public]);$c=$q->fetch();if(!$c)fam_json_response(404,['error'=>'not_found']);
if($method==='GET'){$m=$pdo->prepare('SELECT public_id,author_type,body,delivery_status,created_at FROM portal_conversation_messages WHERE conversation_id=? ORDER BY created_at');$m->execute([$c['id']]);fam_json_response(200,['conversation'=>$c,'messages'=>$m->fetchAll()]);}
if(!in_array('respond_harry',$staff['capabilities'],true))fam_json_response(403,['error'=>'staff_capability_required']);fam_require_attendee_csrf();$d=fam_read_json_body();$body=fam_required($d,'message',5000);$status=(string)($d['status']??'waiting_attendee');if(!in_array($status,['assigned','waiting_attendee','waiting_committee','resolved'],true))fam_json_response(422,['error'=>'validation_error']);
$messagePublic=fam_uuid_v4();$delivery='internal';$pdo->beginTransaction();try{$pdo->prepare("INSERT INTO portal_conversation_messages(public_id,conversation_id,author_type,author_attendee_id,body,delivery_status) VALUES (?,?,'committee',?,?,'internal')")->execute([$messagePublic,$c['id'],$staff['attendee_id'],$body]);$pdo->prepare('UPDATE portal_conversations SET status=?,assigned_to=? WHERE id=?')->execute([$status,$staff['attendee_id'],$c['id']]);if(!empty($c['email'])){fam_queue_portal_email($pdo,'conversation-reply:'.$messagePublic,$c['email'],'Committee reply: '.$c['subject'],fam_portal_email_shell('The reunion committee replied','<p>'.nl2br(htmlspecialchars($body,ENT_QUOTES,'UTF-8')).'</p><p>Sign in to your attendee portal to keep the conversation together.</p>'),'committee');$delivery='queued';$pdo->prepare("UPDATE portal_conversation_messages SET delivery_status='queued' WHERE public_id=?")->execute([$messagePublic]);}fam_portal_staff_audit($pdo,$staff,'conversation_replied','conversation',$public,['status'=>$status,'delivery'=>$delivery]);$pdo->commit();fam_json_response(200,['ok'=>true,'delivery'=>$delivery,'status'=>$status]);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
