<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/_bootstrap.php';
$method=fam_portal_json_method(['GET','POST','PATCH','DELETE']);$staff=fam_require_portal_staff($pdo,'manage_event_content');
if($method==='GET'){$games=$pdo->query("SELECT public_id,title,instructions,status,question_seconds,starts_at,closes_at,created_at FROM trivia_games WHERE status<>'archived' ORDER BY created_at DESC")->fetchAll();$questions=$pdo->query("SELECT q.public_id,g.public_id game_id,q.prompt,q.choices_json,q.correct_index,q.explanation,q.points,q.sort_order,q.status FROM trivia_questions q JOIN trivia_games g ON g.id=q.game_id WHERE q.status<>'retired' ORDER BY g.id DESC,q.sort_order,q.id")->fetchAll();foreach($questions as &$q){$q['choices']=json_decode((string)$q['choices_json'],true);unset($q['choices_json']);}fam_json_response(200,['games'=>$games,'questions'=>$questions]);}
fam_require_attendee_csrf();$d=fam_read_json_body();$type=fam_enum($d,'type',['game','question'],true);
if($method==='POST'&&$type==='game'){$public=fam_uuid_v4();$title=fam_required($d,'title',200);$instructions=fam_required($d,'instructions',1000);$seconds=max(10,min(120,(int)($d['question_seconds']??30)));$pdo->prepare("INSERT INTO trivia_games(public_id,title,instructions,question_seconds) VALUES (?,?,?,?)")->execute([$public,$title,$instructions,$seconds]);fam_portal_staff_audit($pdo,$staff,'trivia_game_created','trivia_game',$public);fam_json_response(201,['ok'=>true,'id'=>$public]);}
if($method==='POST'&&$type==='question'){$gamePublic=fam_required($d,'game_id',36);$g=$pdo->prepare("SELECT id,status FROM trivia_games WHERE public_id=?");$g->execute([$gamePublic]);$game=$g->fetch();if(!$game)fam_json_response(404,['error'=>'not_found']);if($game['status']==='open')fam_json_response(409,['error'=>'game_open']);$choices=$d['choices']??[];if(!is_array($choices)||count($choices)<2||count($choices)>6)fam_json_response(422,['error'=>'validation_error']);$choices=array_map(fn($v)=>trim(substr((string)$v,0,240)),$choices);if(in_array('',$choices,true))fam_json_response(422,['error'=>'validation_error']);$correct=(int)($d['correct_index']??-1);if(!array_key_exists($correct,$choices))fam_json_response(422,['error'=>'validation_error']);$public=fam_uuid_v4();$pdo->prepare("INSERT INTO trivia_questions(public_id,game_id,prompt,choices_json,correct_index,explanation,points,sort_order,status) VALUES (?,?,?,?,?,?,?,?,'draft')")->execute([$public,$game['id'],fam_required($d,'prompt',500),json_encode(array_values($choices)), $correct,trim(substr((string)($d['explanation']??''),0,1000)),max(1,min(1000,(int)($d['points']??100))),max(0,(int)($d['sort_order']??0))]);fam_portal_staff_audit($pdo,$staff,'trivia_question_created','trivia_question',$public,['game_id'=>$gamePublic]);fam_json_response(201,['ok'=>true,'id'=>$public]);}
$public=fam_required($d,'id',36);
if($method==='PATCH'&&$type==='game'){$status=fam_enum($d,'status',['draft','open','closed','archived'],true);if($status==='open'){$q=$pdo->prepare("SELECT COUNT(*) FROM trivia_questions q JOIN trivia_games g ON g.id=q.game_id WHERE g.public_id=? AND q.status='published'");$q->execute([$public]);if((int)$q->fetchColumn()<1)fam_json_response(409,['error'=>'no_published_questions']);$pdo->exec("UPDATE trivia_games SET status='closed' WHERE status='open'");}$q=$pdo->prepare("UPDATE trivia_games SET status=? WHERE public_id=? AND status<>'archived'");$q->execute([$status,$public]);if(!$q->rowCount())fam_json_response(404,['error'=>'not_found']);fam_portal_staff_audit($pdo,$staff,'trivia_game_'.$status,'trivia_game',$public);fam_json_response(200,['ok'=>true]);}
if($method==='PATCH'&&$type==='question'){$status=fam_enum($d,'status',['draft','published','retired'],true);$q=$pdo->prepare("UPDATE trivia_questions q JOIN trivia_games g ON g.id=q.game_id SET q.status=? WHERE q.public_id=? AND g.status<>'open'");$q->execute([$status,$public]);if(!$q->rowCount())fam_json_response(409,['error'=>'not_found_or_game_open']);fam_portal_staff_audit($pdo,$staff,'trivia_question_'.$status,'trivia_question',$public);fam_json_response(200,['ok'=>true]);}
if($method==='DELETE'){$table=$type==='game'?'trivia_games':'trivia_questions';$q=$pdo->prepare("UPDATE {$table} SET status=? WHERE public_id=?");$q->execute([$type==='game'?'archived':'retired',$public]);if(!$q->rowCount())fam_json_response(404,['error'=>'not_found']);fam_portal_staff_audit($pdo,$staff,'trivia_'.$type.'_archived','trivia_'.$type,$public);fam_json_response(200,['ok'=>true]);}
fam_json_response(405,['error'=>'method_not_allowed']);
