(function(){
  'use strict';
  const api=window.PortalApi;
  async function boot(){
    const session=await api.session();if(!session.staff?.capabilities?.includes('manage_event_content'))return;
    const nav=document.querySelector('.workspace-nav');const main=document.querySelector('#workspace-main');if(!nav||!main)return;
    const link=document.createElement('a');link.href='#trivia';link.dataset.section='trivia';link.textContent='Trivia studio';nav.querySelector('[data-section="content"]')?.before(link);
    const panel=document.createElement('section');panel.dataset.panel='trivia';panel.hidden=true;panel.innerHTML=`<div class="section-heading"><div><p class="eyebrow">Reusable engagement module</p><h2>Trivia studio</h2><p>Create a round, add reviewed questions, publish them, then open the game. Correct answers never enter the attendee payload.</p></div></div><div class="dashboard-grid dashboard-grid--forms"><form class="portal-form compact" data-trivia-game-form><h3>New game</h3><label>Title<input name="title" required maxlength="200"></label><label>Instructions<textarea name="instructions" required maxlength="1000"></textarea></label><label>Seconds per question<input name="question_seconds" type="number" min="10" max="120" value="30"></label><button class="button button--primary">Create draft game</button></form><form class="portal-form compact" data-trivia-question-form><h3>Add question</h3><label>Draft game<select name="game_id" required data-trivia-games></select></label><label>Question<input name="prompt" required maxlength="500"></label><label>Choices, one per line<textarea name="choices" required rows="5"></textarea></label><label>Correct answer number<input name="correct_index" type="number" min="1" max="6" required></label><label>Explanation<textarea name="explanation" maxlength="1000"></textarea></label><button class="button">Add draft question</button></form></div><div class="staff-list" data-trivia-admin-list></div>`;main.append(panel);
    async function load(){const data=await api.staffTrivia(),games=data.games||[],questions=data.questions||[];panel.querySelector('[data-trivia-games]').innerHTML=games.filter(g=>g.status==='draft'||g.status==='closed').map(g=>`<option value="${g.public_id}">${g.title}</option>`).join('');panel.querySelector('[data-trivia-admin-list]').innerHTML=games.map(g=>`<article class="staff-row"><div><h3>${g.title}</h3><p>${g.status} · ${questions.filter(q=>q.game_id===g.public_id).length} questions</p><div class="record-actions">${g.status!=='open'?`<button class="button" data-game-status="open" data-id="${g.public_id}">Open game</button>`:`<button class="button" data-game-status="closed" data-id="${g.public_id}">Close game</button>`}</div>${questions.filter(q=>q.game_id===g.public_id).map(q=>`<div class="record-field"><strong>${q.prompt}</strong><small>${q.status} · ${q.points} points</small>${q.status==='draft'?`<button class="text-button" data-question-status="published" data-id="${q.public_id}">Publish question</button>`:''}</div>`).join('')}</div></article>`).join('')||'<div class="staff-empty">Create the first trivia game.</div>';}
    panel.addEventListener('submit',async event=>{event.preventDefault();const fd=new FormData(event.target);if(event.target.matches('[data-trivia-game-form]'))await api.staffTriviaCreate({type:'game',title:String(fd.get('title')),instructions:String(fd.get('instructions')),question_seconds:Number(fd.get('question_seconds'))});else await api.staffTriviaCreate({type:'question',game_id:String(fd.get('game_id')),prompt:String(fd.get('prompt')),choices:String(fd.get('choices')).split(/\n+/).map(v=>v.trim()).filter(Boolean),correct_index:Number(fd.get('correct_index'))-1,explanation:String(fd.get('explanation')||'')});event.target.reset();await load();});
    panel.addEventListener('click',async event=>{const game=event.target.closest('[data-game-status]'),question=event.target.closest('[data-question-status]');if(game){await api.staffTriviaUpdate({type:'game',id:game.dataset.id,status:game.dataset.gameStatus});await load()}if(question){await api.staffTriviaUpdate({type:'question',id:question.dataset.id,status:question.dataset.questionStatus});await load()}});
    link.addEventListener('click',()=>{document.querySelector('[data-coach-title]').textContent='Run a fair, memorable trivia round';document.querySelector('[data-coach-lesson]').textContent='Draft and review the question bank before opening the game. Scoring is server-side, and each attendee gets one recorded attempt.';document.querySelector('[data-coach-checklist]').innerHTML='<li>Review every answer and explanation</li><li>Publish questions before opening the round</li><li>Close the game before making changes</li>';document.querySelector('[data-coach-boundary]').textContent='Trivia attempts and answers are audit evidence; retire or archive them instead of silently rewriting completed play.';load();});await load();
  }
  boot().catch(()=>{});
})();
