(function(){
  'use strict';
  const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
  const api=window.PortalApi, staffViews=new Set(['committee','review','people','inbox','communications','operations']);
  const copy={committee:['Committee operations','Committee Desk','Run the reunion without losing your own attendee experience.','12-clipboard.png'],review:['Private until approved','Review queue','Protect every story before it goes public.','18-presenting.png'],people:['Protected reunion records','People','Find attendees and understand their reunion context.','06-listening.png'],inbox:['Shared response desk','Committee inbox','Make every attendee question accountable.','06-listening.png'],communications:['Consent-aware delivery','Communications','Send the right message to the right people.','16-conducting.png'],operations:['From order to the door','Tickets & operations','Monitor tickets, check-in and exceptions.','13-ticket-stub.png']};
  let staff=null, currentMode='attendee', loaded=new Set();
  const esc=v=>{const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML};
  function unavailable(target,label){const el=$(target);if(el)el.innerHTML=`<div class="staff-empty"><strong>${esc(label)} is not connected yet</strong><p>The secured staff endpoint did not supply this data. No placeholder records are being shown.</p></div>`}
  function roleLabel(role){return role==='site_owner'?'Site Owner':role==='committee_lead'?'Committee Lead':'Committee Member'}
  function metric(value,label,detail){return `<article class="staff-metric"><strong>${esc(value??0)}</strong><span>${esc(label)}</span><small>${esc(detail)}</small></article>`}
  function showContext(data){const el=$('[data-staff-context]');if(!el||!data?.data_context)return;el.textContent=data.data_context.label;el.hidden=false}
  function showStaff(name){if(!staff?.authorized||!staffViews.has(name))return;currentMode='staff';$$('[data-view-panel]').forEach(p=>p.classList.toggle('is-active',p.dataset.viewPanel===name));$$('[data-route]').forEach(a=>a.toggleAttribute('aria-current',a.dataset.route===name));const [eye,title,lead,pose]=copy[name];$('[data-view-eyebrow]').textContent=eye;$('[data-view-title]').textContent=title;$('[data-view-lead]').textContent=lead;$('[data-harry]').src=`../assets/mascot/${pose}`;$('[data-mode-label]').textContent='My Reunion';history.replaceState(null,'',`#${name}`);load(name);window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'})}
  function returnToAttendee(){currentMode='attendee';$('[data-mode-label]').textContent='Committee Desk';const link=$('[data-route=home]');link?.click()}
  async function load(name,force=false){if(loaded.has(name)&&!force)return;loaded.add(name);try{
    if(name==='committee'){const d=await api.staffDashboard(),s=d.summary||{};showContext(d);$('[data-staff-summary]').innerHTML=metric(s.production_rsvps,'Production RSVPs','Imported read-only snapshot')+metric(s.production_menu_selections,'Dinner selections','Imported read-only snapshot')+metric(s.unanswered_messages,'Awaiting reply','Portal and Harry questions')+metric(s.historical_surveys,'Historical surveys','Imported reference records')+metric(s.pending_reviews,'Needs review','Private portal submissions')+metric(s.active_attendees,'Portal accounts','Verified portal identities')+metric(s.operations_attention,'Needs attention','Ticket and delivery exceptions')}
    if(name==='review'){const d=await api.staffReviewQueue($('[data-staff-filter=review]')?.value),items=d.items||[];$('[data-staff-list=review]').innerHTML=items.length?items.map(i=>`<article class="staff-row" data-review-item="${esc(i.public_id)}"><div><h3>${esc(i.title||'Untitled submission')}</h3><p>${esc(i.submitter_name||'Attendee')} · ${esc(i.type||'memory')}</p><div class="staff-row-meta"><span>${esc(i.status)}</span><span>${i.consent_to_publish?'Consent recorded':'Consent not recorded'}</span><span>${esc(i.created_at)}</span></div></div><div class="staff-row-actions"><button class="button button--primary" type="button" data-review-status="approved">Approve</button><button class="button" type="button" data-review-status="rejected">Return</button></div></article>`).join(''):'<div class="staff-empty"><strong>Queue clear</strong><p>No submissions match this filter.</p></div>'}
    if(name==='people'){/* Search runs only when requested to avoid exposing an unnecessary roster. */}
    if(name==='inbox'){const d=await api.staffInbox(),rows=d.threads||[];showContext(d);$('[data-inbox-count]').textContent=`${rows.reduce((n,r)=>n+(Number(r.unread_count)||0),0)} unread`;$('[data-staff-list=inbox]').innerHTML=rows.length?rows.map(r=>`<button class="staff-row" type="button" data-thread="${esc(r.public_id)}"><div><h3>${esc(r.subject||'Attendee message')}</h3><p>${esc(r.participant_name)} · ${esc(r.source||'message')}</p><div class="staff-row-meta"><span>${esc(r.status)}</span><span>${esc(r.updated_at)}</span></div></div><strong>${esc(r.unread_count||'')}</strong></button>`).join(''):'<div class="staff-empty"><strong>Inbox clear</strong><p>No conversations require attention.</p></div>'}
    if(name==='communications'){const d=await api.staffCommunications(),v=d.delivery||{};$('[data-staff-delivery]').innerHTML=metric(v.sent,'Sent','Provider accepted')+metric(v.failed,'Failed','Requires review')}
    if(name==='operations'){const d=await api.staffOperations(),s=d.summary||{};$('[data-staff-operations]').innerHTML=metric(s.pending_orders,'Pending orders','Awaiting completion')+metric(s.active_tickets,'Active tickets','Valid entitlements')+metric(s.checked_in,'Checked in','Arrival count')+metric(s.exceptions,'Exceptions','Needs owner or committee action')}
  }catch(e){loaded.delete(name);const targets={committee:'[data-staff-summary]',review:'[data-staff-list=review]',inbox:'[data-staff-list=inbox]',communications:'[data-staff-delivery]',operations:'[data-staff-operations]'};unavailable(targets[name],name==='committee'?'Committee dashboard':name)}}
  async function boot(){try{const session=await api.session();const candidate=session.staff||null;if(!candidate?.authorized)return;staff=candidate;const toggle=$('[data-mode-switch]');toggle.hidden=false;$('[data-mode-label]').textContent='Admin Portal';toggle.addEventListener('click',()=>{location.href='/portal/admin/'});/* Administrative work lives in one capability-filtered application. */}catch(_){/* Fail closed: attendee UI remains unchanged. */}}
  document.addEventListener('click',e=>{const link=e.target.closest('[data-route]');if(!link||!staffViews.has(link.dataset.route)||!staff?.authorized)return;e.preventDefault();e.stopImmediatePropagation();showStaff(link.dataset.route)},true);
  $('[data-staff-filter=review]')?.addEventListener('change',()=>{loaded.delete('review');load('review')});
  $('[data-staff-list=review]')?.addEventListener('click',async e=>{const button=e.target.closest('[data-review-status]'),row=e.target.closest('[data-review-item]');if(!button||!row)return;button.disabled=true;try{await api.staffAction({action:'review_media',submission_id:row.dataset.reviewItem,status:button.dataset.reviewStatus,note:''});row.remove();loaded.delete('committee')}catch(error){button.disabled=false;row.insertAdjacentHTML('beforeend',`<p class="integration-notice"><strong>Review was not saved.</strong> ${esc(error.message||'Try again.')}</p>`)}});
  $('[data-staff-search=people]')?.addEventListener('submit',async e=>{e.preventDefault();const list=$('[data-staff-list=people]'),q=new FormData(e.currentTarget).get('q')||'';list.innerHTML='<div class="staff-loading" role="status">Searching protected records…</div>';try{const d=await api.staffPeople(q),rows=d.people||[];showContext(d);list.innerHTML=rows.length?rows.map(p=>`<article class="staff-row"><div><h3>${esc(p.name)}</h3><p>${esc(p.email)}</p><div class="staff-row-meta"><span>RSVP: ${esc(p.rsvp_status||'unknown')}</span><span>Ticket: ${esc(p.ticket_status||'none')}</span><span>${esc(p.source==='production_rsvp'?'Production snapshot':'Portal')}</span>${p.access_role?`<span>${esc(p.access_role)}</span>`:''}</div></div></article>`).join(''):'<div class="staff-empty"><strong>No matches</strong><p>Try another name, email, ticket or RSVP detail.</p></div>'}catch(_){unavailable('[data-staff-list=people]','People search')}});
  boot();
})();
